### PR TITLE
Add DnsControl, opinionated system for managing DNS configurations.

### PR DESCRIPTION
**Pull request by meitar**
### Application name / category
[DnsControl](https://stackexchange.github.io/dnscontrol/) / Domain management

### Source URL
https://github.com/stackexchange/dnscontrol

### why it is awesome
DnsControl massively simplifies the process of managing multiple DNS assets (domain names, SRV records, TXT records, SPF entries, etc) by describing those settings "as code," so that they can be stored in a version control repository independent of their deployment. I.e., you can write your DNS-related data in code and then automatically deploy those changes to your own BIND servers or a DNS provider such as Amazon Route53 or CloudFlare. This is especially useful if your infrastructure utilizes multiple providers.

### CODE REVIEW

**Comment by n1trux** [comment]
all these solutions only support a very limited set of DNS providers.

See also #290.

**Comment by meitar** [comment]
> all these solutions only support a very limited set of DNS providers.

Really? Because at the moment, AFAICT, this awesome list contains exactly zero DNS-as-code tools, so a tool that supports this important sysadmin best practice workflow with even one provider would increase this list's references of it by an infinite amount.

Moreover, DnsControl supports (among exactly 15 additional providers) BIND directly, which makes it an excellent choice for completely self-managed infrastructures.

I agree there could be more providers supported, but given as it seems to me to be the case that the current number of providers supported by tools referenced in this awesome list is zero, this addition (or the one in #290) seems obviously valuable.

**Comment by meitar** [comment]
On second thought, I'm not going to bother spending the time advocating for the inclusion of tools like this here. I'm just gonna maintain a fork on my own. This list is fantastic (thanks for all your maintenance of it in the past) and has served me really well, so it makes sense that I'll just start maintaining [a copy for my own use](https://github.com/meitar/awesome-sysadmin).

**Comment by ad-m** [comment]
> awesome list contains exactly zero DNS-as-code tools

Terraform there is it.

**Comment by n1trux** [comment]
>Moreover, DnsControl supports (among exactly 15 additional providers) BIND directly, which makes it an excellent choice for completely self-managed infrastructures.

I overlooked that passage because you're too verbose. I'll include DnsControl.

**Comment by meitar** [comment]
> you're too verbose.

Or do you not read closely? 🤔

**Comment by n1trux** [comment]
maybe that, too :woman_shrugging:

**Pull request closed without merging**
