### PR TITLE
Remove Sentry

### PR DESCRIPTION
**Pull request by ardichoke**
It is not awesome as it is not open source.

### CODE REVIEW

**Comment by cmmata** [comment]
@ardichoke yes, it is: https://github.com/getsentry/sentry

**Comment by lenovouser** [comment]
Of course it is open source?

**Comment by ardichoke** [comment]
See #196 

Only parts of it are opensource and it's copyrighted. It does not meet the qualifications.

**Comment by cmmata** [comment]
Okay, you're right in copyright. It's a pity. Anyway, for your interest, I use both sentry.io with personal projects and open-source version in my company, and I don't see too much differences. It is fully functional.

**Comment by n1trux** [comment]
It is indeed copyrighted, as you can see in the LICENSE file in the repository. That you can read the source doesn't mean it's Open Source by most definition.

My definition includes the right to modify and redistribute, so no, that shit's not OSS ;)

**Pull request merged**
