### PR TITLE
Remove bitnami which is not a Open Source software

### PR DESCRIPTION
**Pull request by FGRibreau**

### CODE REVIEW

**Comment by n1trux** [comment]
Link to license information?

**Comment by FGRibreau** [comment]
@n1trux I am sorry I can't even find it, on wikipedia it says they are under apache licence but source is needed. They clearly are not open-source, see: https://github.com/bitnami

**Comment by n1trux** [comment]
well, not having a github repo doesn't mean a software isn't open source :)
I couldn't find anything either. Let's research further...

**Comment by joubertredrat** [comment]
Bitnami is "PaaS", provide applications intro "containers", you can install yourself or deploy on EC2 or another IaaS providers.
Bitnami use another open source project but Bitnami isn't open source project. I know bitnami since was created, is similar to [Turkney Linux](http://www.turnkeylinux.org/).

**Comment by FGRibreau** [comment]
@joubertredrat :+1:

**Comment by joubertredrat** [comment]
@n1trux , This case is basically the same as that one that told you. https://github.com/n1trux/awesome-sysadmin/issues/50

**Comment by joubertredrat** [comment]
@n1trux , This case is basically the same as that one that told you. https://github.com/n1trux/awesome-sysadmin/issues/50

**Comment by n1trux** [comment]
okay then :)

Thanks for clearing that up!

**Pull request merged**
