### PR TITLE
Add Barman to the backup tool list

### PR DESCRIPTION
**Pull request by mdedonno1337**
Add Barman to the backup tool list

### CODE REVIEW

**Comment by n1trux** [comment]
Your PR is shit, see contribution guidelines.

>Include application names, categories and a link to the open source project page in the description.
>Write a short text why the application you're adding is actually awesome.
>Put only stuff on the list you or another contributor can personally recommend

Added this anyway because it seems useful for PostgreSQL admins.

**Comment by mdedonno1337** [comment]
Your reponse is shit, see the politness guideline.
Accepted anyway, because I dont F* care.

**Comment by n1trux** [comment]
No problem, thanks for your contribution!

**Comment by ulgens** [comment]
@n1trux Did you really change @mdedonno1337 's comment?

**Comment by mdedonno1337** [comment]
@ulengs seems yes, and this way accepting that his first response was not acceptable (same structure of the response, so same idea).

**Comment by n1trux** [comment]
Please, more drama.

Tell me how it wasn't acceptable. "Shit" is a perfectly acceptable word for your PR, because you didn't adhere to the guidelines of this repo.

If you can't or don't want to handle that, just don't write PRs anymore, especially to this repository. It's a simple list, idk why you couldn't go through the 2 minute effort to make your PR pretty.

**Pull request merged**
