### PR TITLE
Add 'Awesome SysAdmin @ LibHunt' to the Resources/Websites section

### PR DESCRIPTION
**Pull request by StanBright**
https://sysadmin.libhunt.com is based on the list here, and is pointing back to this repo as the official one.

### CODE REVIEW

**Comment by n1trux** [comment]
Where exactly is it pointing back? I didn't find a link both in the header and the footer, only the project title. This could be confusing because kahun's repo isn't maintained but still more popular star-wise.

**Comment by StanBright** [comment]
There are links both in the "About" and "Contribute" sections. 

Yet, I think it will be useful to be listed in the "Resources/Websites" section. The projects are listed by popularity and dev-activity, and they can be compared with one another. People have found those features very useful so far.

**Comment by n1trux** [comment]
Sorry, but I don't see the links…

In the about section there's no link to this repo:

about

And clicking the link "contribute" only tells me there is a PR/Issue tracker, which is here, but that's not really a link back.

contribute

I don't see the relevancy for this site being in the list because it's nothing else than the list itself and you can discover plenty of awesome stuff by clicking on the "awesome" badge right beside the project's name.

This PR will be closed, but feel free to discuss further.

**Comment by StanBright** [comment]
Hi @n1trux, I am sorry. My bad. I mean the "About" page.

screen shot 2016-09-07 at 9 26 55 am
---
I agree that it's a kind of list. However, I'd say an enhanced list. Here they are some of the benefits.

- The projects are ordered by popularity by default, and that is very helpful when someone is researching. Moreover, you have some nice and useful graphs on the top of every category. e.g. [Long Management](https://sysadmin.libhunt.com/categories/1742-log-management)
- People can order the projects by development activity, and that is also an important factor when choosing a new library.
- You can compare libraries from the same category e.g. [Fluent vs LogStash](https://sysadmin.libhunt.com/project/fluentd/vs/logstash)

I still believe that sysadmin.libhunt.com is relevant to this repo, and many people will find it useful.

In the end, @n1trux, you are the maintainer of the repo, and it's you who have to decide. I am just asking to have a look again and maybe reconsider. If you wish, maybe we can put it for a vote?

**Comment by n1trux** [comment]
If this PR gets enough likes or other people think that your site is awesome, I'll probably merge it. Let's just wait and see.

**Comment by StanBright** [comment]
Thumbs up!

**Comment by Darksider3** [comment]
"Like" (Obv, the backlinks could be more ... Offensive, but hey. We're at Facebook here. Like!)

**Comment by pszlazak** [comment]
Worth to add it.

**Pull request merged**
