### PR TITLE
add Datadog monitoring guides to the websites section

### PR DESCRIPTION
**Pull request by vagelim**
[Datadog](https://github.com/DataDog/dd-agent) is an open source tool for metrics collection, written in Python. 

The [Datadog blog](https://datadoghq.com/blog) is a compendium of well-researched, peer-reviewed monitoring guides. The monitoring guides are vendor-neutral, and detail not only the most important metrics to collect for a particular technology, but also how to collect those metrics using native tools, or third-party open source tools.

Please let me know if a direct link to the blog is innapropriate; the research team at Datadog also maintains a [repository](https://github.com/DataDog/the-monitor) for all of the longform monitoring guides which may be more appropriate for inclusion in this list.

### CODE REVIEW

**Comment by n1trux** [comment]
I think this website/blog is a bit too specific for this repository. We already have datadog as entry in the monitoring section, maybe we should just add a "(guides here)" or similar behind it.

**Comment by nodiscc** [comment]
I would add it as \[[1](https://datadoghq.com/blog)\] behind the datadog entry.

    \[[1](https://datadoghq.com/blog)\]

**Comment by vagelim** [comment]
Shall I close this PR and open a new one with [this change](https://github.com/n1trux/awesome-sysadmin/pull/184#issuecomment-251085754)?

**Comment by n1trux** [comment]
you can rebase and squash your commits or you could open a new one, whatever you like :)

**Comment by vagelim** [comment]
@n1trux I could not find a Datadog entry in the README as it is (though it's entirely possible that I am under-caffinated). Please see the corresponding PR: https://github.com/n1trux/awesome-sysadmin/issues/194

**Pull request closed without merging**
