### PR TITLE
add XenServer in Virtualization

### PR DESCRIPTION
**Pull request by olivierlambert**
XenServer is not just plain Xen: it's a complete "turnkey" distro which embed Xen and a powerful toolstack/API. And it's FOSS.

### CODE REVIEW

**Comment by n1trux** [comment]
can you add the "turnkey distro" and on what Linux distribution it's based to the description?

>turnkey virtualisation platform based on X Linux distribution

or sth along the lines. Thanks!

**Comment by olivierlambert** [comment]
Done!

**Comment by n1trux** [comment]
thank you very much for your fast response :)

**Comment by olivierlambert** [comment]
No problem, I've got another PR coming when I'll have enough time :) See you soon ;)

**Pull request merged**
