### PR TITLE
Add Micro

### PR DESCRIPTION
**Pull request by Angristan**
### Application name / category
[Micro](https://micro-editor.github.io/) / Editors

### Source URL
https://github.com/zyedidia/micro

### why it is awesome
Easy to use but powerful. A good compromise between nano and vim!

### CODE REVIEW

**Comment by ad-m** [comment]
Duplicate of #182

**Comment by Angristan** [comment]
Sorry, I should have checked.

15 months later, I guess micro has gained more popularity and features. 

About the installation, it's now available trough brew, chocolatey, scoop, snap, AUR and pkg_add. I wonder if it's enough for @n1trux, otherwise we'll wait for it to come into some main Linux distro repositories :)

**Comment by n1trux** [comment]
I'll add it when it's in the main repos.

**Comment by Angristan** [comment]
Ok.

I just found out it was also available in Solus trough eopkg. (https://dev.solus-project.com/source/micro/)

**Pull request merged**
