### PR TITLE
Add Smallstep Certifications, a personal CA toolkit for SSO TLS & SSH.

### PR DESCRIPTION
**Pull request by meitar**
### Application name / category
[Smallstep Certifications](https://smallstep.com/certificates/) / Identity Management

### Source URL
https://github.com/smallstep/certificates

### why it is awesome
Easily manage enterprise-wide distrubtion of X.509 certificates for both TLS-secured services and SSH hosts.

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
I assume you read this blog post, too.
https://smallstep.com/blog/use-ssh-certificates/

**Comment by meitar** [comment]
> I assume you read this blog post, too.
https://smallstep.com/blog/use-ssh-certificates/

More importantly, I *didn't* read any mention of this tool in prior pull requests or issues.

**Comment by SuperSandro2000** [comment]
> More importantly, I _didn't_ read any mention of this tool in prior pull requests or issues.

Is this a good or bad thing? Do you think it isn't well battle tested or even buggy or just a hidden gem?

**Comment by meitar** [comment]
> Is this a good or bad thing? Do you think it isn't well battle tested or even buggy or just a hidden gem?

By submitting a pull request, I would have thought it obvious to that I think this tool should be on this list, much like [like DnsControl](https://github.com/n1trux/awesome-sysadmin/pull/289) and [octoDNS](https://github.com/n1trux/awesome-sysadmin/pull/290), which are already listed on my fork of this project.

Perhaps I ought simply not attempt to be generous with my time and attention in this space and instead reserve my energies for places where I am not unneccessarily asked to answer pointless questions.

**Comment by n1trux** [comment]
Please don't take it personally if your contributions get criticised.

**Comment by meitar** [comment]
> Please don't take it personally if your contributions get criticised.

I think that instead of chiding contributors to your own project, you should be telling the bottom-half-of-the-Internet [who have never contributed to this work in the past and do not seem to be contributing](https://github.com/n1trux/awesome-sysadmin/search?q=SuperSandro2000) not to non-constructively and needlessly criticize contributions. Failing to do that sets a very bad precedent and is a big, bright red flag for the kind of person you are, along with how you maintain a project.

Precisely why I forked this and maintain my own copy.

**Comment by alexpdr** [comment]
Yeah one look at your profile @meitar tells us exactly the person you are, jikes. Don't be the fragile snowflake hating the world, it helps no one.

And thanks to @n1trux for the repo and patience.

**Comment by meitar** [comment]
> Yeah one look at your profile @meitar tells us exactly the person you are, jikes. Don't be the fragile snowflake hating the world, it helps no one.

I rest my case.

**Comment by n1trux** [comment]
I removed insults by @meitar and @alexpdr. I won't allow personal attacks here.

**Pull request merged**
