### PR TITLE
Add SWMP to "Monitor" Section

### PR DESCRIPTION
**Pull request by fuzzymannerz**
Would be great if you could add SWMP to the list?

### CODE REVIEW

**Comment by n1trux** [comment]
You recommend piping curl into bash, which is not awesome in my eyes.

**Comment by fuzzymannerz** [comment]
https://github.com/fuzzymannerz/swmp#installation also shows a more conventional `wget` method.

The method you are referencing exists for the convenience of one-line, if you can suggest a better way of doing it with the same result, I'm all ears.

**Comment by pszlazak** [comment]
Here is how it is done [during Node.js installation](https://nodejs.org/en/download/package-manager/):  
`curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -`

**Comment by Darksider3** [comment]
https://www.seancassidy.me/dont-pipe-to-your-shell.html Think describes one of the problems with piping curl/wget into bash; The other one is simply: How do you make sure, if you can't see any of the shell code executed there, what it is *really* doing?

It's like curl http://example.com | sudo bash .... 

Thats **Awful*

**Comment by fuzzymannerz** [comment]
Ahh thanks guys, interesting, I'll have a read of those for sure!

So I'll just stick to this then considering it's a direct link to the file anyway so you could just open it with an editor before running it if you were wanting to see exactly what it does..:

```
wget https://getswmp.thefuzz.xyz/install.sh && chmod +x install.sh && ./install.sh
```

**Comment by n1trux** [comment]
Nice, guys. Thanks for changing this :) merged.

**Pull request merged**
