### PR TITLE
Add xiringuito - SSH-based "VPN for poors"

### PR DESCRIPTION
**Pull request by ivanilves**
### Application name / category
xiringuito / VPN

### Source URL
https://github.com/ivanilves/xiringuito

### why it is awesome
`xiringuito` is awesome, because:
* easy to install (no dependencies, no configurations)
* allows you to manage one, few or many connections easily (and connect em simultaneously if you want)
* it has `xaval` connection manager - a tool that may record and later re-use your connection profiles
* though you are free to use or not to use `xaval` connection manager - people also use `xiringuito` for ad-hoc onetime connections
* Just look at this GIF :wink:

### CODE REVIEW

**Comment by ivanilves** [comment]
Hey, any reason why we can not merge this? :wink:

ping @n1trux 

Thanks! :heart:

**Comment by n1trux** [comment]
it's your own software, it's a hack and you need sudo rights.

Did you [tell](https://github.com/sshuttle/sshuttle/issues?utf8=%E2%9C%93&q=rtp) the developers of sshuttle that RTP doesn't work over their SSH tunnel?

Why not use [the methods outlined in the Arch Wiki "VPN over SSH" entry](https://wiki.archlinux.org/index.php/VPN_over_SSH)? There's also pvpn mentioned there, how is xiringuito better than pvpn?

**Comment by ivanilves** [comment]
> it's your own software, it's a hack and you need sudo rights.

yes && yes && yes && I (and not only I) still believe it's awesome :wink: 

_OpenVPN, PPP, L2TP, almost everything except maybe sshuttle - also do need sudo rights, no?_

> Did you tell the developers of sshuttle that RTP doesn't work over their SSH tunnel?

I didn't. There is no sense. Look, they do not support UDP (RTP works over UDP) for FreeBSD and MacOSX at all and I see no recent efforts to fix it. See this pretty recent issue: https://github.com/sshuttle/sshuttle/issues/155 

Also: sometimes I need to work with lower-level protos like OSPF and ARP, which will never work in sshuttle cause it does not expose tun devices like xiringuito does. It's not a sshuttle flaw, it's just a way how it works, which happened to be different from what I need.

> Why not use the methods outlined in the Arch Wiki "VPN over SSH" entry? There's also pvpn mentioned there, how is xiringuito better than pvpn?

I have not used anything from the link below because essentially it **requires to create a static configuration for every tunnel** you plan to use. For many people who have 1-3 tunnels it's OK. I have hundreds of tunnels, some configurations I use for years, some only for days and never return to them. 

How xiringuito is better than **pvpn** etc? 
Well, `xiringuito` is:
* dynamic (it makes auto-magic decisions how to configure routing and DNS for U) 
* no configuration required (does not waste your time on creating config files)
* you may save and later re-use your connections with bundled `xaval` CLI if you want
* you may disable all the magic if you want (by passing corresponding command line options)

_xiringuito "auto-magic" works perfectly on predictable environments like Amazon or Google clouds, still could work decently on on-premise private systems, but you will need to tune it a bit. But still this automation saves time. (almost?) all "VPN over SSH" articles on the net assume you will have one tunnel for all your life and their ways are very limited, that's why I've created xiringuito and that's why I believe it's awesome - it saves time by just making connections and not asking you to create lots of bogus files, install pppd etc_

> EDIT: Oh, and I just found out it doesn't have a Free license so by definition it's not awesome enough to put on this list.

Hey, thanks for noticing this! I've added an Apache version 2 license now.

> And any serious FOSS project shouldn't have smileys in their README because it's overhead.

Highly controversial statement I would say! What is the definition of serios FOSS project?

**Comment by n1trux** [comment]
Thanks for your clarifying statement. I still feel the project isn't quite as mature as I'd like projects on this list to be. For example, there's no packaging in any of the major distributions, but you're already working on it (ivanilves/xiringuito/issues/16). Let's see how this plays out.

>Look, they do not support UDP (RTP works over UDP) for FreeBSD and MacOSX at all and I see no recent efforts to fix it. See this pretty recent issue: sshuttle/sshuttle#155

There one dev says "PRs welcome". Why not just try to find a good solution and post a PR? NIH syndrome?

>_still could work decently on on-premise private systems, but you will need to tune it a bit_

What exactly does that mean? Is there documentation for this?

>I've added an Apache version 2 license now.

Cool, thank you.

>Highly controversial statement I would say!

If you say so.

I for one dislike [emojis as commit messages](/ivanilves/xiringuito/commit/0099035909ee6126b6ab4465a1b85c18700e9751) because they're senseless, useless and don't actually tell you what happened. It's nice that you're one of the cool kids, but __just don't__. A lot of people won't take your project seriously this way and you won't be able to land PRs in more popular projects with this practice.

Just like I currently can't take your project seriously and won't include it in this "awesome" list _just yet_.

**Comment by ivanilves** [comment]
Well, yes, your point on "needs to mature" actually makes sense.

> There one dev says "PRs welcome". Why not just try to find a good solution and post a PR? NIH syndrome?

* not everybody likes/knows python...
* NIH (of course, NIH is not only a major "cancer" of Open Source, but also a major innovation engine ... sometimes)

> What exactly does that mean? Is there documentation for this?

I provide a primer with https://github.com/ivanilves/xiringuito/blob/master/discover-routes.aws.example
and a note https://github.com/ivanilves/xiringuito#route-discovery Any actual environment-specific edits are up to end-user. It is really easy - the discovery script only needs to print the routes to `STDOUT` so xiringuito will pick up them and use. However what's inside the discovery script is up to user, not up to me.

> I for one dislike emojis as commit messages

OK, you picked one particular emoji abuse case, YES. :laughing: 

In general emojis are not as bad (depends on your preferences, there are no "correct"/"incorrect", the World is a diverse place). And I am OK with some people not taking my project seriously and, of course, when I open PRs to other projects I follow their rules, my rules are only for my personal projects. :wink:

Thanks for your input! It was really useful and really helped me to plan further development of `xiringuito`

For now I'm closing this PR. I think we could re-open it in some future.

**Pull request closed without merging**
