### PR TITLE
Add Cloudron to Control Panels -> Server

### PR DESCRIPTION
**Pull request by nebulade**
### Cloudron - Control Panel
[Cloudron](https://cloudron.io) / Control Panels -> Server

### Source URL
https://git.cloudron.io/cloudron/box

### why it is awesome
Cloudron will manage everything needed to run apps or webservices on a Linux server. It uses docker in the backend for isolation. Furthermore it comes with a full email server solution.

### CODE REVIEW

**Comment by n1trux** [comment]
>Note: This repo is a small part of what gets installed on your server - there is
the dashboard, database addons, graph container, base image etc. Cloudron also relies
on external services such as the App Store for apps to be installed. As such, don't
clone this repo and npm install and expect something to work.

You have to pay for your service, this is not awesome. Will close this, solutions like Rancher or KubeSpray allow you to self-host all parts of the equation. Feel free to comment on this if I got this all wrong.

**Comment by nebulade** [comment]
The note you have quoted is mostly there to not expect users to clone that repo, do some package installation and run some daemons, instead one should use the installer script, which pulls in more than just this repo. Also Cloudron works just fine also without paying and there is a supported free tier anyways, similar to Virtualmin (which is also listed) the pricing for the supported version comes in when certain usage numbers are hit (domain count or app count). Also note that for Cloudron this only applies to officially supported apps installed from our provided library (where all app package code is also open source), you may use it to deploy as many of your custom packaged apps as you like. So overall I don't see what the large difference is, wrt to being awesome.

**Comment by n1trux** [comment]
This is not at all clear on your homepage or in your repo. Where's the "custom packaged apps" documentation up front?

Also, I scrolled a bit further down in the repo and clicked on the "self-hosted" link. You somehow need a DNS service out of a list for this to work. They're all non-selfhosted options:

>AWS Route53, Cloudflare, Digital Ocean, Gandi, GoDaddy, Google Cloud DNS, name.com, Wildcard.

Furthermore, the App Store seems to require an account on your site:

>When you click on the App Store link in the UI, you will be prompted to create a cloudron.io account. This account is used to manage your subscription & billing.

So no, apparently it is __not__ possible to self-host this without being dependent on a "Cloud Service".

>similar to Virtualmin (which is also listed) the pricing for the supported version comes in when certain usage numbers are hit

Somehow I'm not able to find this on the GPL vs Pro comparison site of Virtualmin.](https://www.virtualmin.com/vs). If you're sure about this, you're free to create a PR to remove Virtualmin with a link to proof, I'll review this and merge if positive.

**Comment by nebulade** [comment]
From what I understand in the [pricing page](https://www.virtualmin.com/buy/virtualmin) of Virtualmin, they only allow 7 installable apps, this is very similar to Cloudron. I think for both projects, the culprit is the supported vs. unsupported case. Given the open source nature, it is possible to circumvent all this, with the tradeof of having to spend more time understanding all the components involved to get the system working well. 

You are correct about the appstore account requirement, but only if you wish to install apps from the supported library. If you want to deploy apps manually using the Cloudron cli tools, then no account is required. The documentation about APIs and packaging can be found at https://cloudron.io/developer/packaging/ . The visibility may not be the best, I agree.

Overall is this awesome list about pure selfhosting, like without even using a non-selfhosted DNS provider or a docker hub to pull images? If so, then given the scope of Cloudron, which will always be dependent somehow on external services, which may or may not be selfhostable (like backup to loal filesystem, minio or AWS S3), I see how it would not be a fit for this list.

**Comment by n1trux** [comment]
>If you want to deploy apps manually using the Cloudron cli tools, then no account is required.

Well, then I could also just use `docker-compose` ;)

>Virtualmin […] allow 7 installable apps, this is very similar to Cloudron

As far as I see it, they only allow 7 different software packages being installed, but you can install an unlimited amount of instances and servers with them. And not just two apps and five users as stated on https://cloudron.io/pricing.html.

>Free: 0 $/mo, 2 Apps, 5 Cloudron Users, Automatic Updates, Email Solution

>Basic: 15 $/mo, 20 Apps, 30 Cloudron Users, Automatic Updates, Email Solution, Priority Support

With Cloudron you have to pay even for the GPL version, as stated on https://cloudron.io/documentation/billing/:

>For selfhosted, we charge on a 30 day subscription basis (prepaid). Any charges will be made on the first day of the 30 day period. Any service can be cancelled at any time, the service will then be terminated at the end of the current 30 days period.

This list is about awesome admin tools and I don't see any point of including it, since it doesn't make my life any easier without paying X amount of money.

>is this awesome list about pure selfhosting, like without even using a non-selfhosted DNS provider or a docker hub to pull images

No, https://github.com/Kickball/awesome-selfhosted would be about selfhosting and Cloudron is already [on that list since 2016](https://github.com/Kickball/awesome-selfhosted/#714). IMHO Cloudron fits that list more than awesome-sysadmin.

>without […] a non-selfhosted DNS provider or a docker hub to pull images?

As far as I'm concerned it's okay to have a 3rd party service, **_if_** you can self-host everything. I already retracted my statement about DNS as you can clearly self-host a wildcard DNS entry with Cloudron and it'll work.

My problem is that your App Store (equivalent to Docker Hub) **requires sign-up** and even payment, while alternatives like _Docker Hub, Flockport, LXD_ et al. are all either free or you can self-host an app store. Self-hosting an App Store doesn't seem to be possible with Cloudron.

And even if it was, the documentation seems to be subpar and hides the open source aspects of the project fairly well. I don't want to recommend projects with that kind of documentation to my users. I'm currently thinking about removing Virtualmin from my list.

**Comment by swelljoe** [comment]
Don't drag us (Virtualmin) into this. Our Open Source version has no usage/domain/etc. limits and requires no payments or accounts or cloud services or whatever to use. It is under the GPL license and is fully self-hosted (if you want to self host it).

There is a supported commercial version includes a few extra features and some additional installable web apps, but the free version is really Free.

**Comment by nebulade** [comment]
I'm sorry, I didn't mean to bring Virtualmin in as a negative example or such. I thought of the list as awesome sysadmin helper tools, which Virtualmin of course is as well, so it absolutely should be listed here. I didn't expect a commercial offering, which a project pushes for as the preferred option for users, is a blocker. Of course it is up to the list maintainer to decided what is awesome or not in his view for this list.

**Pull request closed without merging**
