### PR TITLE
Add BorgBackup to backup software

### PR DESCRIPTION
**Pull request by elnappo**
BorgBackup is a fork of Attic. Attic seams to not be actively maintained anymore. Borg added a tone of new features and many bugfixes.

> * more open, faster paced development (see [issue #1](https://github.com/borgbackup/borg/issues/1))
* lots of attic issues fixed (see [issue #5](https://github.com/borgbackup/borg/issues/5))
* less chunk management overhead (less memory and disk usage for chunks index)
* faster remote cache resync (useful when backing up multiple machines into same repo)
* compression: no, lz4, zlib or lzma compression, adjustable compression levels
* repokey replaces problematic passphrase mode (you can't change the passphrase nor the pbkdf2 iteration count in "passphrase" mode)
* simple sparse file support, great for virtual machine disk files
* can read special files (e.g. block devices) or from stdin, write to stdout
* mkdir-based locking is more compatible than attic's posix locking
* uses fadvise to not spoil / blow up the fs cache
* better error messages / exception handling
* better logging, screen output, progress indication
* tested on misc. Linux systems, 32 and 64bit, FreeBSD, OpenBSD, NetBSD, Mac OS X

https://github.com/borgbackup/borg

### CODE REVIEW

**Comment by n1trux** [comment]
since borg is a nice name for a backup solution and attic seems to be pretty buggy (in fact, I tried it and changed to rsnapshot instead a few days after), could you please remove the attic link, too?

**Comment by elnappo** [comment]
Of course. Should I mention the fork and python?

**Comment by n1trux** [comment]
yes please :)

**Comment by elnappo** [comment]
Done

**Pull request merged**
