### PR TITLE
Add Duplicati

### PR DESCRIPTION
**Pull request by StefanZi**
Tool: Duplicati
Category: Backups
Website: http://www.duplicati.com
Awesome because: FLOSS software, multiple platforms (.NET/MONO-based), easy to use backup on all important cloud services (like OneDrive, Amazon S3...) and other backends (including ftp, ssh...) combined with built-in AES encryption.

### CODE REVIEW

**Comment by n1trux** [comment]
I'll add this when 2.0 is finally out and ready.

**Comment by StefanZi** [comment]
I am using version 2 in production already to make use of the 1TB OneDrive cloud storage you get as O365 user. I am very happy with the quality and there is the stable 1.x branch, too.
So perhaps give it a second thought, otherwise I'm happy with having this awesome tool added with the stable release of v2.

**Comment by n1trux** [comment]
Duplicati 2.0 is in beta now! Doesn't seem to be long until we can include it as awesome backup solution :)

The only thing which keeps me from adding is their own statement:

>In 2017 we focused on all kinds of issues that you had with Duplicati 2.0 to make it a safe and reliable backup solution. We are happy that we can say, there was no safety issue at any time. But we had to fix a few issues in situations where the remote backup data got corrupted. We are still working to improve such situations.

https://www.duplicati.com/news/Beta-Announcement/

They seem to put in the same care about the most important part of data safety as me, I'm looking forward to a stable 2.0 and will definitely test the beta.

**Comment by Darksider3** [comment]
Some progres coming in: https://forum.duplicati.com/t/2nd-beta-version-of-duplicati-2-0-now-available/3085
Still not out of beta, though

**Comment by n1trux** [comment]
ok so… I deployed this countless times over the last 2 years in several SMBs, so far everything worked. There are [some minor roadblocks on the way to 2.0 stable](https://github.com/duplicati/duplicati/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.0+stable%22), so I'm adding a small reference to that.

**Comment by n1trux** [comment]
er… github doesn't seem to understand what I wanted to do here. Thank you for contributing, Duplicati is on the list. If you somehow manage to find out where I fucked up I'd be happy if you'd let me know :sweat_smile:

**Pull request closed without merging**
