### PR TITLE
Add Wireguard to the VPN section

### PR DESCRIPTION
**Pull request by rhyven**
### Application name / category
[WireGuard](https://www.wireguard.com/) / VPN

### Source URL
https://git.zx2c4.com/WireGuard/

### why it is awesome
Wireguard is a new VPN based on elliptic curve crypto (Curve25519, ChaCha20, Poly1305) and public key cryptography. It has a very small attack surface and is extremely fast. It's currently used in production by Mullvad VPN and AzireVPN.

### CODE REVIEW

**Comment by ad-m** [comment]
It's not awesome yet.

See https://www.wireguard.com/ : 
> WireGuard is not yet complete. You should not rely on this code. It has not undergone proper degrees of security auditing and the protocol is still subject to change. We're working toward a stable 1.0 release, but that time has not yet come. There are experimental snapshots tagged with "0.0.YYYYMMDD", but these should not be considered real releases and they may contain security vulnerabilities (which would not be eligible for CVEs, since this is pre-release snapshot software). If you are packaging WireGuard, you must keep up to date with the snapshots.

**Comment by rhyven** [comment]
It's pretty awesome!  But fair enough.  I understand v1 is fairly close - happy for me to resubmit this ticket once it's released?

**Comment by ad-m** [comment]
I do not have permission to perform merge, so I also decide, but I think the official release of the application is a mandatory criterion. Let's promote good, stable software, and not slogans and advertising (without taking away WireGuard, which I watch with great interest too).

**Comment by n1trux** [comment]
Thanks for pointing it out, @ad-m.

Thanks and proceed as proposed, @rhyven. Just resubmit when it's out of beta. Good Pull Request, btw :)

**Comment by rhyven** [comment]
Thanks, @n1trux!  And will do  :)

**Comment by n1trux** [comment]
re-opened because:
* I want to avoid duplicates
* I want to track this in a sensible manner
* this was the first proper PR for wireguard

I'd love if you were to keep your fork open until wireguard gets a release @rhyven :)

**Comment by rhyven** [comment]
Cool, thanks @n1trux!  Will do!  :)

**Comment by jakehemmerle** [comment]
Wireguard has been merged into the Linux kernel as of Jan 28, 2020. Should this get merged now?
Primary source: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=bd2463ac7d7ec51d432f23bf0e893fb371a908cd

Sourced from: https://en.wikipedia.org/wiki/WireGuard

**Comment by ad-m** [comment]
Is there an explanation of the effects of including changes to the kernel in the absence of self-confidence in the project? The message about CVE deficiencies due to the lack of final release is still on the WireGuard project website, which should be the primary source of information about the project.

**Pull request merged**
